spring:
  profiles:
    active: sandbox

---
spring:
  profiles: sandbox
  data:
    mongodb:
      host: localhost:27017
      database: nInsite
      uri: mongodb://localhost:27017/nInsite
    web:
      pageable:
        default-page-size: 100

naver:
  client:
    id: ZbKLbYIpl_FPc8x08Gxi
    secret: EyOgY5ddDN
---